### ISSUE TITLE
Add raw support for as_emld

### ISSUE THREAD

**Issue by isteves** [ropensci/emld#19]
Since we often get EML from dataone/etc as raw, it would be great to support that functionality with `read_eml`/`as_emld`.  We typically read it in [this way](https://nceas.github.io/datateam-training/reference/get-package-and-eml.html) (`eml <- read_eml(rawToChar(dataone::getObject(mn, "doi:10.18739/A2K86G")))`), though I'm now realizing that the rawToChar part isn't necessary (anymore?).

It seems that `read_eml`/`as_emld` could be expanded with:

- this addition to [`as_emld.character`](https://github.com/cboettig/emld/blob/7f261ae24a10340161d5c431216bc39e3832fb9a/R/as_emld.R#L19): `if (grepl("\\.xml$", x) | grepl("<|>", x))` (since [read_xml](https://github.com/r-lib/xml2/blob/b2bd3e77f5d29270f50aa98e9623fc1d5d9588f2/R/xml_parse.R) already handles it)
- an `as_emld.raw` method, which could also piggyback off of read_xml: 

```
as_emld.raw <- function(x){
        x <- xml2::read_xml(x)
        as_emld.xml_document(x)
}
```
Happy to PR it if you think this makes sense

**Comment by cboettig** [comment]
Yeah, that makes sense to me. Can you send a PR with unit test showing how this works on a raw object?
