### ISSUE TITLE
fix EML 2.2.0 namespace

### ISSUE THREAD

**Issue by jeanetteclark** [ropensci/emld#39]
currently the namespace is listed as eml://ecoinformatics.org/eml-2.2.0, but I believe it should be https://eml.ecoinformatics.org/eml-2.2.0

**Comment by cboettig** [comment]
Thanks.  I could use more clarification on that issue -- is the switch from `eml://` to the `https://` an extension or does it deprecate the use of `eml`?  Is that just for 2.2.0 or also for 2.1.1?  (I note that https://eml.ecoinformatics.org/eml-2.1.1 doesn't resolve, but then an XML namespace doesn't need to, and it's not necessarily the same thing as the `schemaLocation`.  

Obviously this appears in lots of places (including all the test files, e.g. https://github.com/ropensci/emld/blob/master/inst/tests/eml-2.2.0/eml-i18n.xml and also for 2.1.1).  I'm happy to migrate (or have a PR for migration) but it's potentially a lot to change so we should do with care.  

Further discussion welcome on this!!

cc @amoeba @mbjones

**Comment by jeanetteclark** [comment]
Hey Carl - I honestly don't know enough to answer your questions but here are relevant discussions that might help: 

https://github.com/NCEAS/eml/issues/341
https://github.com/NCEAS/eml/issues/334

**Comment by amoeba** [comment]
Hey @cboettig, it's a change only applied to the 2.2.0 release and it's something I expect we'll continue in future releases. The canonical URI for 2.1.1 and earlier are unchanged and still use the `eml` URI scheme. The change was a recognition that having a URI that also resolves is better than holding onto our custom URI scheme.

I'll take a look and send a PR today.

**Comment by cboettig** [comment]
nice thanks, a PR updating that would be great.  The test files probably just needs to be re-synced with the EML 2.2.0 release test files, or at least also get their namespace updated (maybe a little `sed -i`....)  The logic might assume that namespace can be determined from the version string alone, so might need a bit of extra work to make sure it switches the whole namespace prefix when the version env var is set.

**Comment by amoeba** [comment]
Took a look at this and I think I only have a couple more things to tweak. Straightforward so far. Working over at https://github.com/amoeba/emld/tree/eml-220-ns-fixes. Will be done tomorrow.

**Comment by jeanetteclark** [comment]
@amoeba while you are in there, should we switch the default version back to 2.2.0?

https://github.com/ropensci/emld/issues/31

**Comment by amoeba** [comment]
I put this down and just now got back to it, sorry about the delay. I ended up finding quite a few places to tweak things but my initial tests look good. @cboettig since you're the most familiar with the package, can you give this my incoming PR a whirl some time? I updated the automated tests and testdocs, and did some manual testing.
