### ISSUE TITLE
additional validation errors

### ISSUE THREAD

**Issue by mbjones** [ropensci/emld#48]
I found additional validation errors in addition to #46.

1) The `packageId` is not used as an identifier for checking uniqueness with other `id` values and for resolving references.
2) Errors are thrown for `annotation` elements in `additionalMetadata` because their parent doesn't contain an `id`. This should be ok, because in `additionalMetadata` the annotation subject is determined via the `describes` fields.
3) The `annotation/@references` attribute values are not checked during validation to be sure they resolve to an `id` -- only the `//references` elements are checked.

I've begun implementing fixes for these in my fork here: https://github.com/mbjones/emld/tree/46-validation-errors

**Comment by mbjones** [comment]
Fixes checked in PR #49 .

**Comment by cboettig** [comment]
Closed by #49 

Please let me know if now would be a good time to prepare a CRAN release for these changes? Or shall we hold tight and see if there's any remaining validation issues we can squash first?


@mbjones would you be willing to send another PR with updates to NEWS.md describing the validator changes?  Also, the DESCRIPTION author list is now out of date -- may I add you and @amoeba as co-authors there?

**Comment by mbjones** [comment]
I think another release now would be good -- those were serious errors and we should get them out into the community so that there's less confusion over correct validation.

I'll send another PR and update both files, and I'll bump the version to 0.4.0 in DESCRIPTION.  Do you want to run `codemetar` again or just update the codemeta.json file manually with the additional info?

**Comment by cboettig** [comment]
Thanks!

Feel free either way on the `codemeta`, I run the codemetar script at submission anyway.
